### ISSUE TITLE
Flatten the directory structure

### ISSUE THREAD

**Issue by vhavlena** [VeriFIT/nfa-bench#1]
Is it possible to flatten the directory structure? My suggestion:

- get rid of all `gen_aut` directories
- kick off `.emp` files to a separate top-level directory. Mingling data with the operations is not a good idea I think. I perceive this repo as a collection of automata
- remove directories of the form `[0-9]*`. Does it really provide some information? The same for `0-1-17-25-35` inside `email_filter`

**Comment by tfiedor** [comment]
Sounds good. I will implement these changes and simplify the directory structure. I will also remove some duplicate automata, this will result into e.g. email filter to be flattened to approx 50 automata only (since `0-1-2-3-4` represents operation with automata `0-4`).

**Comment by tfiedor** [comment]
@vhavlena can you check PR #2 ? I flattened the structure considerably, is that better or can you think of some other changes?

I removed .emp files altogether after some thinking, also I kept subdirectories for cox/ere/intersect, rest should be flat. There will be some dupes though, I could run `fdupes` to filter them out (these were due to the fact, that some automata were reused for some inclusion/intersection/etc operations).
